name: server
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  shelf_modular: ^1.0.0
  dartz: ^0.10.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
